name: 'String Generation'
description: 'Generate a string'
inputs:
  string-to-print:  # id of input
    description: 'String to print'
    required: true
    default: 'This is the default string'
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.string-to-print }}.
      shell: bash