name: 'String Generation'
description: 'Generate a string'
inputs:
  string-to-print:  # id of input
    description: 'String to print'
    required: true
    default: 'This is the default string'
outputs:
  output1: 
    value: ${{ steps.step1.outputs.string }}
runs:
  using: "composite"
  steps:
    - id: step1
      run: echo "string=${{ inputs.string-to-print }}." >> $GITHUB_OUTPUT
      shell: bash